apiVersion: v1
kind: Service
metadata:
  name: julian
  labels:
    created-by: julian
spec:
  selector:
    app: julian
  ports:
    - protocol: TCP
      port: 8000      
      targetPort: 8080 
  type: ClusterIP
